### ISSUE TITLE
Enable custom Read Status types

### ISSUE THREAD

**Issue by Dominic-DallOsto** [Dominic-DallOsto/zotero-reading-list#12]
Allow the user to define a custom list of Read Status types.

How should these interact with the icons and keyboard shortcuts? Maybe we only allow the first 9 options to have keyboard shortcuts. And it should be possible to allow any unicode character (like ⭐) for the icons.

**Comment by Yam0214** [comment]
Hey, thanks for your working. The 'Read Status' column works better for me than original tags. 

I kindly request your assistance in implementing the enhancement feature mentioned in this issue. I‘m used to taking a quick look at the paper upon its inclusion in Zotero, and then read the papers intensively one by one. So, it would greatly benefit me if I could customize my own status types to distinguish between the two reading states.

**Comment by gothamgreen** [comment]
Seconded :).
