### ISSUE TITLE
Compatibility with Zotero7

### ISSUE THREAD

**Issue by POBrien333** [Dominic-DallOsto/zotero-reading-list#13]
Hi,
As the Zotero 7 beta has been released, I wanted to find out if your plugin is compatible with it or when you think you could make it compatible?

**Comment by Dominic-DallOsto** [comment]
I've updated the extension for Zotero 7. If you have the chance, you can test download the beta version [here](https://github.com/Dominic-DallOsto/zotero-reading-list/releases/tag/v1.0.0-beta). Let me know if you have any feedback!

**Comment by williamberrios** [comment]
I tested and it works. Thank you for your contribution.
<img width="805" alt="image" src="https://github.com/Dominic-DallOsto/zotero-reading-list/assets/37418346/38fedccf-da05-476e-9036-9e8f21daba84">
