### ISSUE TITLE
Unable to display reading status

### ISSUE THREAD

**Issue by CowboyH** [Dominic-DallOsto/zotero-reading-list#14]
Thanks for the open source plugin. But I am not able to display the reading status in the preview screen after installing the plugin following the steps you provided. I'm using zotero 6.0.30. there is still only the title and creator in the preview screen, there is no way to achieve the same effect as in your screenshot.

**Comment by devzhk** [comment]
Same here. Zotero 6.0.30 doesn't display reading status.

**Comment by williamberrios** [comment]
Thanks for this plugin @Dominic-DallOsto. I am also observing the same problem. Is there any way to fix this? Thanks in advance, this is such a great plugin.

**Comment by williamberrios** [comment]
Hi @Dominic-DallOsto, thank you for taking a look. I downloaded the beta Zotero7 (7.0.0-beta.58+2665090aa). However, I cannot see the icons (screenshot attached). I have followed the steps indicated in the README. Any idea?
<img width="1116" alt="image" src="https://github.com/Dominic-DallOsto/zotero-reading-list/assets/37418346/8586699c-0f18-4a6b-94e6-c313a71730a9">

**Comment by Dominic-DallOsto** [comment]
Ahh, you need to right click on the item pane column header (ie. where it says "Title" and "Creator"), then enable the Read Status column

![image](https://github.com/Dominic-DallOsto/zotero-reading-list/assets/26859884/a3f4c936-76d6-4463-a0df-b063a8e6581a)

I'll add these instructions to the README

**Comment by williamberrios** [comment]
Awesome!! I can see it now! thanks @Dominic-DallOsto ❤️
