### ISSUE TITLE
cannot download add-on from webpage

### ISSUE THREAD

**Issue by liyuf486** [Dominic-DallOsto/zotero-reading-list#15]
Hi! Thanks so much for this amazing add-on. There's a problem with my device - the column for 'read status' does not show icons with colors anymore so I was hope to reinstall this add-on to see if it's going to get back to normal. The downloading link from the webpage doesn't work so I was hope if you could fix the link.
Would also be grateful if you could just lmk how to get the color back to the icons:
![图片](https://github.com/Dominic-DallOsto/zotero-reading-list/assets/152659094/75630fe3-ea2d-483a-859d-369be2db4aae)
thanks!

**Comment by Dominic-DallOsto** [comment]
Which operating system are you using? I think this looks like a bug with firefox on your OS.

**Comment by MoRoBe-Work** [comment]
Did you try right click -> "Save Link As"?

**Comment by Dominic-DallOsto** [comment]
Let me know if you encounter this problem again!
