### ISSUE TITLE
 The reading status of some pdfs is not displayed.

### ISSUE THREAD

**Issue by GemmaWW** [Dominic-DallOsto/zotero-reading-list#21]
Hi, thanks a lot for this add-on that helps me to be more efficient! 

I'm using it and I've noticed that it's working properly on most of my reading projects, but not on certain pdfs. For these pdfs, they are not showing up no matter which reading state I check. I am not sure what is wrong. Is there any way to get these pdfs to show the normal reading status as well please?

( I am using zotero 7, with windows 11.

**Comment by Dominic-DallOsto** [comment]
Ahh, this won't work on raw PDFs, only if you have them saved as attachments to Zotero items. 

That the menu shows up when right clicking on a PDF / other attachment is just a bug, sorry

**Comment by 812088491** [comment]
> Ahh, this won't work on raw PDFs, only if you have them saved as attachments to Zotero items.
> 
> That the menu shows up when right clicking on a PDF / other attachment is just a bug, sorry.
> 
> There doesn't seem to be an easy way to fix this with the current API for adding the right click menu, but maybe it'll be added.

Thanks for the explanation, very helpful! Best wishes to you!
