### ISSUE TITLE
Cannot set Custom Read Statuses and Icons

### ISSUE THREAD

**Issue by MicReed** [Dominic-DallOsto/zotero-reading-list#24]
Greetings, the feature for tracking reading progress is excellent. However, I'm unable to customize read statuses. There isn't a "Setting" option under "Edit," only "Preferences," and there are no settings available for the Zotero Reading List under preferences.

I'm using Zotero version 6.0.36 on Windows and Reading List for Zotero version 0.3.2.

![image](https://github.com/Dominic-DallOsto/zotero-reading-list/assets/60501042/ec793efe-6701-40b1-95f1-168a436310dc)

**Comment by Dominic-DallOsto** [comment]
Ahh sorry, the custom read statuses are only present in the Zotero 7 version of this extension.

To make it compatible with Zotero 6 would require a lot of extra work and I would like to focus on the future version of the extension.

I'll add a note to the README about this though!

**Comment by MicReed** [comment]
Thank you for your reply. I'll give Zotero 7 a try, though I'm concerned about its compatibility with my current work and add-ons.

**Comment by Dominic-DallOsto** [comment]
Yeah, I don't think all popular addons are updated yet unfortunately
