### ISSUE TITLE
Keyboard shortcuts to assign statuses on MacOS

### ISSUE THREAD

**Issue by adamslc** [Dominic-DallOsto/zotero-reading-list#33]
I see that Alt + <num> can be used to assign a reading status to an item. However, MacOS does not have an Alt key, and using the Option key instead does not seem to work. Is there some other keyboard shortcut that works, and if not can this functionality be added?

**Comment by Dominic-DallOsto** [comment]
Hi yeah, this is a known issue (see #9)

I'm not able to test on a mac unfortunately - could you follow the instructions in the last post of that issue and let me know what happens (and your Zotero version). Thanks!
