### ISSUE TITLE
Icons not displayed right

### ISSUE THREAD

**Issue by SlaenderManPhy** [Dominic-DallOsto/zotero-reading-list#37]
Hi,

The icons in my Read Status are not displayed correctly. Is there any way to solve this?

Thank you!

(Zotero versuib 6.0.36)

![image](https://github.com/user-attachments/assets/40d825d2-9f24-4e32-9fff-ecbcd4afa5a7)

**Comment by Dominic-DallOsto** [comment]
Hmmm, I just tested with Zotero 6.0.36 on Windows 10 and I can't replicate this. The icons appear coloured for me.

It looks like your Zotero is somehow defaulting to an older set of icons.

Which version of Windows are you using? And can you see these icons rendered in colour in your browser?

`⭐ New, 📙 To Read, 📖 In Progress, 📗 Read, 📕 Not Reading`

**Comment by SlaenderManPhy** [comment]
Thank you for your reply, i have windows 11, and yes, i can see the icons rendered in my browser.

**Comment by Dominic-DallOsto** [comment]
Which language are you using under Edit -> Preferences -> Advanced -> General -> Miscellaneous -> Language?

Does the same happen if you change the language?

**Comment by SlaenderManPhy** [comment]
I am using english, i tried changing it to german and restarted zotero. However, the issue still remains.

**Comment by Dominic-DallOsto** [comment]
What if you paste one of the icons into the title of an item for example? Or into a random textbox input in the settings? Does it show in colour there?

**Comment by SlaenderManPhy** [comment]
It is still in this weird color

![image](https://github.com/user-attachments/assets/a89ae2a4-2414-4ad2-ba9c-35c902cac63e)

**Comment by Dominic-DallOsto** [comment]
Then this seems to be a problem with Zotero itself rather than this plugin. Maybe it's somehow related to font or accessibility settings but I'm not sure.

It'd be best for you to open a question on the [Zotero forums](https://forums.zotero.org/) asking about this (you can also link back to this issue here) and you'll likely find better support.

**Comment by SlaenderManPhy** [comment]
Thank you for your support. I will try and figure this out.

**Comment by Dominic-DallOsto** [comment]
In general yeah, migrating to the Zotero 7 beta might be the best option to try and solve the font problem if there isn't some plugin you rely on that isn't compatible yet or some other reason you can't upgrade.

I don't think there's as much of a focus on maintaining Zotero 6 compared to 7 at the moment.

**Comment by SlaenderManPhy** [comment]
I just switched to version 7 and it works now. :)

**Comment by Dominic-DallOsto** [comment]
Perfect!
