### ISSUE TITLE
Suggestion to shorten "Read Status" to "Progress"

### ISSUE THREAD

**Issue by helsingi** [Dominic-DallOsto/zotero-reading-list#40]
Hi, thanks for the useful plugin. Not sure if my suggestion makes sense or if other users would also like it(?)
The use case / reason for m suggestion is that I view several columns and try to optimize the screen space I have, and the Read Status is actaually very useful column to have shown all the time for me. So I thought it would be nicer to shorten its name to Progress so that I can minimize the column width and make space for the item title etc.

**Comment by Dominic-DallOsto** [comment]
Hi, thanks for your suggestion!

That makes sense that you want a way to view the read status while taking up minimal space. I think for this specific case that "Progress" wouldn't be so much shorter than "Read Status". But I wonder whether you could save even more space by minimising the column width so you can only see the emoji? Would something like this work for you?

![image](https://github.com/user-attachments/assets/e572df95-f114-4450-a3e9-beda8ff0719f)

If you think it would be useful, I could enable you to hide the text of the read statuses so it only shows you the emoji - this would also save you the "..." in each row.

**Comment by helsingi** [comment]
Yes, that is actually much better! I am using Zotero 7 and latest version of the plugin yes.
The option to have only icons is great. Would that also apply to the column title? The column title could be the plugin main icon/logo. It would then look something like the attachement column!

**Comment by Dominic-DallOsto** [comment]
Ok, you can now select preferences to achieve something like below:

![image](https://github.com/user-attachments/assets/6f820092-5f59-4455-b918-0c8c8bf0b7a0)

I hope that's all good!

**Comment by helsingi** [comment]
Looks great! Thanks!
