### ISSUE TITLE
Yet another idea: Pin items

### ISSUE THREAD

**Issue by MaxVonMustermann** [Dominic-DallOsto/zotero-reading-list#51]
Hey there, this is another idea that is only loosely related to Reading list/annotations counter. But since your extensions are well crafted and polished and go in the direction of productivity and interface improvements, I am still going to ask.
Is it theoretically possible to create an extension that allows users to pin items within a collection to the top of the item list? This would be quite helpful, especially for larger collections. Nevertheless, I assume this might be more complicated, since it requires a new feature to be implemented into the interface? Thank you for a response in advance!

**Comment by Dominic-DallOsto** [comment]
Here's a rough version that adds a new column for pinning items https://github.com/Dominic-DallOsto/zotero-pin-items

Using custom sorting is the best that's easily possible. I don't think pinning items so you can still see them when you scroll down would be possible without Zotero itself supporting it.
