### ISSUE TITLE
Cannot be used normally

### ISSUE THREAD

**Issue by Duebassx** [Dominic-DallOsto/zotero-reading-list#58]
In Zotero7, I have to turn off all plugins to use the reading list normally. Why is that?

**Comment by Dominic-DallOsto** [comment]
Hi, can you provide some more details on the issue, or some pictures showing what you mean by it not working normally?

Could you also check the error console when the error occurs (Tools > Developer > Error Console) and let me know what you see?

**Comment by Duebassx** [comment]
I found some problems. As long as I add Translate for Zotero, the reading list will become invalid.
error console：
![1726479345576](https://github.com/user-attachments/assets/a3cd58c3-b726-40ba-a83f-22807ed8de7d)

**Comment by Dominic-DallOsto** [comment]
Hmm OK.

Just to confirm:

- if you disable all extensions and restart Zotero, then enable Translate for Zotero, then enable Zotero Reading List - you see that error message: `this.globalCache is undefined`?
- What happens if you first enabled Zotero Reading List, then enable Translate for Zotero?
- If you restart Zotero with both plugins enabled, do you also see the same error message?

**Comment by Duebassx** [comment]
The picture in the previous reply is the error caused by restarting Zotero with both plugins enabled. And in the first two cases, a warning like this will be added:
![52a36c501677602a669b07cf37a3012](https://github.com/user-attachments/assets/be4d15ae-1318-4c8c-a2c8-c624fd85e086)
I found that after opening the plug-in, there will be the following problem:
![1ab36a0e5e064b7118fcb5dba331ca0](https://github.com/user-attachments/assets/5f4e4bee-d990-4861-9a3a-ad035706a8b4)

**Comment by Duebassx** [comment]
Thank you, I solved the problem after uninstalling and reinstalling

**Comment by Dominic-DallOsto** [comment]
Ok!

Just to confirm - did you reinstall Zotero? Or reinstall the extension?

**Comment by Dominic-DallOsto** [comment]
Just to check whether this might be the same issue as #59 - were you using Zotero for ARM64?

**Comment by AliMashhadi** [comment]
I actually had the same problem. Yesterday I opened zotero and found out that the read status column was gone. After I turned off translate plugin, read status reappeared. I guess read status and translate got updated on themselves. Now I have updated everything including zotero itself, but the problem still insists.

**Comment by Duebassx** [comment]
I have always used the 64-bit version

**Comment by Dominic-DallOsto** [comment]
Hmm, which operating system and which version of Zotero are you both using? Maybe it isn't exclusively an ARM issue

**Comment by thomas-decloedt** [comment]
I'm using Arch Linux (kernel 6.10.7) on x86_64 architecture and Zotero version 7.0.3. It seems this might not be exclusively an ARM issue

**Comment by Dominic-DallOsto** [comment]
Interesting. Can you post which plugins you're using when the error occurs?

And does reinstalling all plugins solve the problem for you too?

**Comment by AliMashhadi** [comment]
I'm using windows 11 (x86 - 64bit) and Zotero 7 (7.0.5 32bit) and according to Zotero all plugins are up to date. Turning off translate plugin fixes the problem.
If I remove and reinstall read status, the status I've already made for articles would disappear?  If not, I can do that.

**Comment by ckenadiao** [comment]
I think I also faced the same issue as well. This time, the external extension causing this problem is Zotero Attanger (disabling this plugin and restart zotero will work). Using ZotMoov on the other hand, doesn't really create this issue.

**Comment by flecheapolinienne** [comment]
Same problem on Windows 11 (x86 - 64bit) and Zotero 7.0.6-beta.2+b4239fd4c (64-bit). The extension only appears to be working when all other are deactivated.

**Comment by Maozhen-Zhang** [comment]
yeah, it's need to close other extension to use reading list

**Comment by allabur** [comment]
Same for Windows 11 64 and Zotero 7.0.5 (64-bit)
![image](https://github.com/user-attachments/assets/58566a0e-90bd-47c1-8bee-590455c227e7)

**Comment by JENMukiri** [comment]
Same problem on Mac M1, Mac OS Sonoma Version 14.0 (23A344),  7.0.7-beta.1+3fcdae8fa. The extension only appears to be working when all other plugins are deactivated.

**Comment by Ea510chan** [comment]
Same Problem on Windows 11, zotero 7.0.5 (64 bit).

**Comment by Marco-Ray** [comment]
Same problem on Windows 10, zotero 7.0.7 (64-bit) with following plugins.
![image](https://github.com/user-attachments/assets/170a2de5-c10b-4bf4-ad72-f7766acae228)

**Comment by Dominic-DallOsto** [comment]
> There seem to be related issues in [github-young/zotero-better-authors#77](https://github.com/github-young/zotero-better-authors/issues/77) [daeh/zotero-markdb-connect#138](https://github.com/daeh/zotero-markdb-connect/issues/138)

Ahh thanks for this! Yeah it definitely looks like this is some weird interaction between plugins that use the same zotero-plugin-scaffold backend. I'll look into this / open an issue there

**Comment by Feng1909** [comment]
Same problem on Ubuntu 20.04.6 LTS and Zotero 7.0.7 (64-bit). The extension only appears to be working when all other are deactivated.

**Comment by Dominic-DallOsto** [comment]
As discussed in https://github.com/windingwind/zotero-plugin-toolkit/issues/64 I tried updating the zotero-plugin-toolkit version which I think was responsible for these errors.

Please check out v1.5.2 and let me know if it fixes the problem!

**Comment by AliMashhadi** [comment]
> As discussed in [windingwind/zotero-plugin-toolkit#64](https://github.com/windingwind/zotero-plugin-toolkit/issues/64) I tried updating the zotero-plugin-toolkit version which I think was responsible for these errors.
> 
> Please check out v1.5.2 and let me know if it fixes the problem!

It's actually fixed! thanks man.

**Comment by allabur** [comment]
Fixed! Thanks 💫

**Comment by Dominic-DallOsto** [comment]
I think this is fixed then!

But if not and you're still encountering this issue, please let me know!
