### ISSUE TITLE
Zotero Reading List not working after changing from Zotero 7 x86 to Zotero 7 ARM64

### ISSUE THREAD

**Issue by Cloddy13** [Dominic-DallOsto/zotero-reading-list#59]
hi sorry to disturb you but it gives me back this error when I installed the Zotero ARM64
![Immagine 2024-09-16 121710](https://github.com/user-attachments/assets/b06f7187-4e6f-4a59-897d-009353f611cc)
Not sure why, it was working before! I'm devastated!

**Comment by Dominic-DallOsto** [comment]
Hmm, this is the same error message as #58. There apparently reinstalling fixed it, so that could be worth trying.

Which version of Zotero are you using, on which platform? You mentioned ARM - is this Windows on ARM or a newer Mac? And which version of the extension do you have?

**Comment by Cloddy13** [comment]
So you mean disinstalling and reinstalling Zotero itself? i'm running Zotero 7 Windows ARM64. For the plugin i have the latest version 1.51.

Thanks

**Comment by Dominic-DallOsto** [comment]
Hmm, were you previously running the 32-bit or 64-bit version of Zotero 7, where this extension worked fine for you? But you just changed over to the ARM64 version of Zotero 7 and then started having this issue?

Could you try to reinstall this plugin and see if it works then?

If that doesn't work, can you try disabling all other plugins except this one and see if that works?

These are just the solutions that worked for #58, but I'm not yet sure why so you'll have to experiment sorry!

**Comment by Cloddy13** [comment]
Yes, I used to run another version, probably th 32bit one and it worked fine. The Zotero warned me it was running in simulation mode and suggested to download and install the ARM64 version which was more suitable for my system requirements. i already tried to uninstall the plugin and reinstall it but with no results. I now disabled the other plugins and Reading List is restored, but I only had two more: better notes and open pdf via zotero...

**Comment by Dominic-DallOsto** [comment]
Ok cool, that narrows things down a bit.

If you also reinstall better notes and open pdf, does Zotero Reading List continue to work when they're enabled?

**Comment by Cloddy13** [comment]
When Better notes is disabled but open pdf not, readling list still seems to work. I will reinstall Better notes and see what happens with a new installation

**Comment by Cloddy13** [comment]
Done, no conflict whatsoever now. Thank you so very much for your prompt responses and support. I love your plugin! it kicks absolutely ass and it's the only thing I wanted since I've discovered Zotero. I could kiss you if you were here!

**Comment by Dominic-DallOsto** [comment]
Hahaha, no worries at all! Good to hear it worked out!

**Comment by Dominic-DallOsto** [comment]
It's possible that this issue wasn't actually related to Zotero on ARM and was actually the same as #58, but it's a bit unclear because I couldn't managed to replicate it
