### ISSUE TITLE
The column order will change after restarting the Zotero 7

### ISSUE THREAD

**Issue by YoushanLiu** [Dominic-DallOsto/zotero-reading-list#66]
Hi, Thank you for your plugin. I have a issue about it.
I use this plugin and I changed the order of the columns provided by the plugin. But each time they are loaded they tend not to load in the order they were in when they were last closed, but in a random order.

**Comment by Dominic-DallOsto** [comment]
Hmmm, could you provide more information? I tried to replicate this but the columns are always in the same order I left them after I restart Zotero.

Which operating system, version of Zotero, and version of this plugin are you using? Do you experience the same problem with other plugins that add custom columns?

**Comment by YoushanLiu** [comment]
@Dominic-DallOsto Thank you for your reply. I use the Zotero 7.0.10 on Windows 11. I found that this problem is caused by the the plugin of the Zotero Citation Count Manager. After I uninstall it, the adjusted order of column title will be preserved after restarting Zotero.
