### ISSUE TITLE
question "Automatically Label New Items" and suggestion

### ISSUE THREAD

**Issue by groele** [Dominic-DallOsto/zotero-reading-list#7]
Thanks a lot for your development, when adding new items to my Zotero library, I want "New" to be turned on by default, .
Feedback: Every time you open the software, you need to re-check "Automatically Label New Items"

Suggestions: 
1. When I open the document, I hope the content of the label will change, for example: form new->reading.
2. Support user-defined reading status keywords
Sincerely thank you for your development and dedication

**Comment by MSBack** [comment]
@Dominic-DallOsto Any update on this?

**Comment by Dominic-DallOsto** [comment]
Because these seem like 3 separate issues, I've split them up to allow for easier discussion:
#10
#11
#12
